# Generated by Django 3.2.7 on 2021-09-05 13:00

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, help_text='Unique Customer ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('balance', models.FloatField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, help_text='Unique Transaction ID', primary_key=True, serialize=False)),
                ('amount', models.FloatField(max_length=100)),
                ('from_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_cid', to='home.customer')),
                ('to_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_cid', to='home.customer')),
            ],
        ),
    ]
