# Generated by Django 3.2.7 on 2021-09-05 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcid', to='home.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcid', to='home.customer'),
        ),
    ]
