# Generated by Django 3.2.7 on 2021-09-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210919_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_cid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_cid',
            field=models.UUIDField(null=True),
        ),
    ]
