# Generated by Django 3.2.7 on 2021-09-19 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210919_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_cid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
