# Generated by Django 3.2.7 on 2021-09-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210919_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='transax',
            field=models.IntegerField(default=0),
        ),
    ]
